# Generated by Django 3.2.25 on 2024-05-17 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternstamp',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patternstamp',
            name='forme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.forme'),
        ),
    ]
