# Generated by Django 3.2.25 on 2024-05-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stamp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.forme')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.type')),
            ],
        ),
    ]
