# Generated by Django 3.2.25 on 2024-05-18 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stamp', '0006_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ContenuStamp', models.CharField(max_length=1024)),
                ('id_Encrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.encrier')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('monture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.monture')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.paiement')),
                ('patternStamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.patternstamp')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stamp.type')),
            ],
        ),
    ]
