# Generated by Django 3.2.25 on 2024-05-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0008_patternstamp_image_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patternstamp',
            old_name='image_example',
            new_name='image',
        ),
    ]
