# Generated by Django 3.2.25 on 2024-05-19 00:26

import Stamp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stamp', '0009_rename_image_example_patternstamp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrier',
            name='image',
            field=models.ImageField(null=True, upload_to=Stamp.models.Encrier_image_file_path),
        ),
        migrations.AddField(
            model_name='monture',
            name='image',
            field=models.ImageField(null=True, upload_to=Stamp.models.Monture_image_file_path),
        ),
    ]
